### ISSUE TITLE
Support SVG to PNG conversion without Inkscape

### ISSUE THREAD

**Issue by asfaltboy** [cassiobotaro/certificates#2]
E.g with something like [Kozea/CairoSVG](https://github.com/Kozea/CairoSVG), by including it in the dependencies and replacing lines

https://github.com/cassiobotaro/certificates/blob/d7465690cc0c76b6624c93df89e76789fb3aa5a2/certificates.py#L45-L49

with something like:

```python
import cairosvg  # put me in the top

new_svg = base_svg.read_text(encoding='utf-8').format(**locals())
png_filename = str(output_filename).replace("svg", "png")
cairosvg.svg2pdf(file_obj=new_svg, write_to=png_filename)
```

**Comment by cassiobotaro** [comment]
I install cairosvg, and test with examples, but the results aren't good.
![joe doe](https://user-images.githubusercontent.com/3127847/39279603-79faf9ac-48d0-11e8-83c7-4a26c2f34798.png)

**Comment by asfaltboy** [comment]
Unfortunately, I know little to nothing about SVG format or Cairo .. could you file a bug in https://github.com/Kozea/CairoSVG/issues with any additional details you have?
